services:
  - type: web
    name: currencies-frontend
    runtime: node
    repo: https://github.com/PatelPratik39/Currencies-App
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
    region: oregon
    buildCommand: cd client && npm install && npm run build
    startCommand: npx serve -s build

  - type: web
    name: currencies-backend
    runtime: node
    repo: https://github.com/PatelPratik39/Currencies-App
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
    region: oregon
    buildCommand: cd Server && npm install
    startCommand: node server.js
