services:
  - type: web
    name: currencies-frontend
    runtime: node
    repo: https://github.com/PatelPratik39/Currencies-App
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
        sync: false
    region: oregon
    buildCommand: cd client && npm install && npm run build
    startCommand: npx serve -s build

  - type: web
    name: currencies-backend
    runtime: node
    repo: https://github.com/PatelPratik39/Currencies-App
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
        sync: false
    region: oregon
    buildCommand: cd server && npm install
    startCommand: node server.js
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
